### ISSUE TITLE
请问作者方便告知一下不同模型的symbols吗？

### ISSUE THREAD

**Issue by LiebeVerletzt** [Kanade-nya/PJSK-MultiGUI#1]
最近在尝试使用插件实现群内实时的文本转语音，但那个插件需要每个模型的独立symbols；我尝试使用占位符输出后是杂乱的音，所以需要原作者训练时的symbols字符组，非常感谢！

**Comment by Kanade-nya** [comment]
（自动回复）邮件已收到。

**Comment by LiebeVerletzt** [comment]
在https://github.com/Kanade-nya/PJSK-Vits-Uni/blob/main/interface.py中找到啦，谢谢作者！
